#!/bin/sh
rm -f src/Makevars configure.log autobrew
find src -name "*.o" -exec rm -f {} +
find src -name "*.a" -exec rm -f {} +
find src -name "*.tmp" -exec rm -f {} +
rm -rf tools/build
rm -rf tools/dist
