# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Build s2Polygons Layers
#' 
#' @param ptrs list with S2Polygons pointers
#' @param b_ptr external pointer with existing build, or NULL
#' @export
s2BuildPolygonsLayer <- function(ptrs, b_ptr) {
    .Call(`_libs2_s2BuildPolygonsLayer`, ptrs, b_ptr)
}

#' convert R vector with coordinates (lon,lat) into S2Point ptr 
#' 
#' @param pt numeric; length 2, longitude latitude
#' @name s2makepoint
#' @export
s2MakePoint <- function(pt) {
    .Call(`_libs2_s2MakePoint`, pt)
}

#' @export
#' @name s2makepoint
#' @param ptrs R list with external references (pointers) to S2Point objects
s2GetPoint <- function(ptrs) {
    .Call(`_libs2_s2GetPoint`, ptrs)
}

#' convert R matrix with coordinates (lon,lat) into S2Polyline ptr 
#' 
#' @param pts 2-column numeric matrix with lng,lat line vertices
#' @name s2makepolyline
#' @export
s2MakePolyline <- function(pts) {
    .Call(`_libs2_s2MakePolyline`, pts)
}

#' @export
#' @name s2makepolyline
#' @param ptrs R list with external references (pointers) to S2Polyline objects
s2GetPolyline <- function(ptrs) {
    .Call(`_libs2_s2GetPolyline`, ptrs)
}

#' convert R list of coordinate matrices (lon,lat) into S2Polygon ptr 
#' 
#' @param mat two-column matrix with longitude in first, latitude in second column
#' @param oriented logical; if TRUE, rings are guaranteed to be oriented (e.g. read
#' by \code{read_sf} using \code{check_ring_dir=TRUE}), meaning CCW exterior rings
#' and CW holes; if FALSE, rings are normalized and holes are deduced from degree of nesting.
#' @name s2makepolygons
#' @export
s2MakePolygon <- function(mat, oriented = FALSE) {
    .Call(`_libs2_s2MakePolygon`, mat, oriented)
}

#' @export
#' @name s2makepolygons
#' @param ptrs R list with external references (pointers) to S2Polygon objects
s2GetPolygon <- function(ptrs) {
    .Call(`_libs2_s2GetPolygon`, ptrs)
}

#' Geometry operators for s2 geometries
#' 
#' @param x list with S2Polygons or S2Polyline pointers
#' @param y list with S2Polygons or S2Polyline pointers
#' @param polygons logical; if TRUE, x and y are S2Polygon, otherwise S2Polyline
#' @name s2ops
#' @export
s2Intersects <- function(x, y, polygons = TRUE) {
    .Call(`_libs2_s2Intersects`, x, y, polygons)
}

#' @export
#' @name s2ops
#' @param ptrs list of S2Polygon or S2Polyline pointers
s2IsValid <- function(ptrs, polygons = TRUE) {
    .Call(`_libs2_s2IsValid`, ptrs, polygons)
}

#' @export
#' @name s2ops
s2GetArea <- function(ptrs) {
    .Call(`_libs2_s2GetArea`, ptrs)
}

s2latlng_from_numeric <- function(lat, lng) {
    .Call(`_libs2_s2latlng_from_numeric`, lat, lng)
}

data_frame_from_s2latlng <- function(xptr) {
    .Call(`_libs2_data_frame_from_s2latlng`, xptr)
}

libs2_cpp_test_indexing <- function() {
    invisible(.Call(`_libs2_libs2_cpp_test_indexing`))
}

